EvaluationApp/Models/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EvaluationApp.Models
{
    public class EmployeeViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Position { get; set; }

        public string Team { get; set; }
    }
}

EvaluationApp/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppServices.EmployeeAuthentication;
using AppServices.Evaluations;
using AppServices.EvaluationsForms;
using AppServices.EvaluationStatistics;
using DomainModel.Domain;
using EvaluationApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EvaluationApp.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IEvaluationFormsService evaluationFormsService;
        private readonly IEvaluationsService evaluationsService;
        private readonly IAuthenticationService authenticationService;
        private readonly IEmployeesService employeesService;
        private readonly IEvaluationStatisticsService evaluationStatistics;


        public EmployeesController(
            IEmployeesService employeeService,
            IEvaluationFormsService evaluationFormsService,
            IEvaluationsService evaluationsService,
            IAuthenticationService authenticationService,
            IEvaluationStatisticsService evaluationStatistics)
        {
            this.evaluationFormsService = evaluationFormsService;
            this.evaluationsService = evaluationsService;
            this.employeesService = employeeService;
            this.authenticationService = authenticationService;
            this.evaluationStatistics = evaluationStatistics;
        }

        public IActionResult Index()
        {
            int loggedEmployeeId = authenticationService.GetCurrentUserId();
            var vm = employeesService.GetEmployeesToEvaluate(loggedEmployeeId);

            return View("Employees", vm);
        }

        [HttpGet]
        public IActionResult StartFormEvaluationModal(int id)
        {
            int currentEmployeeId = authenticationService.GetCurrentUserId();

            var vm = new StartEvaluationViewModel();
            vm.SelectedEmployee = id;
            vm.IsEmployeeEnabled = false;
            vm.Name = "";

            vm.EmployeesList = employeesService.GetEmployeesToEvaluate(currentEmployeeId)
                            .Select(employee =>
                                    new SelectListItem { Text = employee.Name, Value = "" + employee.Id, Selected = (employee.Id == id) })
                            .ToList();
            vm.FormsList = evaluationFormsService.GetEnabledSharedFormsForEmployee(currentEmployeeId)
                           .Select(form =>
                                   new SelectListItem { Text = form.Name, Value = "" + form.Id })
                                   .ToList();
            vm.IsFormEnabled = true;


            return View("StartEvaluationModal", vm);
        }

        [HttpGet]
        public IActionResult ViewEmployeeProgressModal(int id)
        {
            int currentEmployeeId = authenticationService.GetCurrentUserId();

            var vm = new EmployeeProgressViewModel();
            vm.SelectedEmployee = id;
            vm.IsEmployeeEnabled = false;

            vm.EmployeesList = employeesService.GetEmployeesToEvaluate(currentEmployeeId)
                            .Select(employee =>
                                    new SelectListItem { Text = employee.Name, Value = "" + employee.Id, Selected = (employee.Id == id) })
                            .ToList();
            vm.FormsList = evaluationFormsService.GetEnabledSharedFormsForEmployee(currentEmployeeId)
                           .Select(form =>
                                   new SelectListItem { Text = form.Name, Value = "" + form.Id })
                                   .ToList();
            vm.IsFormEnabled = true;


            return View("ViewEmployeeProgressModal", vm);
        }

        [HttpGet]
        public IActionResult EmployeeProgress(EmployeeProgressViewModel vm)
        {
            var form = evaluationFormsService.GetEvaluationForm(vm.SelectedForm);

            var EvaluationFormStatistics = evaluationStatistics.GetStatisticsForFormAndEmployee(vm.SelectedForm, vm.SelectedEmployee);
            return View(EvaluationFormStatistics);
        }

        public IActionResult InProgress(int employeeId)
        {
            var inProgressEvaluations = evaluationsService.GetInProgressEvaluationsForEmployee(employeeId);
            var evaluationViewModels = GenerateEvaluationViewModels(inProgressEvaluations);

            return View(evaluationViewModels);
        }
        public IActionResult Completed(int employeeId)
        {
            var completedEvaluations = evaluationsService.GetCompletedEvaluationsForEmployee(employeeId);
            var evaluationViewModels = GenerateEvaluationViewModels(completedEvaluations);

            return View(evaluationViewModels);
        }

        private EvaluationViewModel GenerateEvaluationViewModel(Evaluation evaluation)
        {
            EvaluationViewModel evaluationViewModel = new EvaluationViewModel
            {
                Id = evaluation.Id,
                EvaluationName = evaluation.EvaluationName,
                FormName = evaluation.FormName,
                IsCompleted = evaluation.IsCompleted,
                Sections = evaluation.Sections,
                Employee = employeesService.GetEmployeeInfo(evaluation.EmployeeId),
                LastEvaluator = employeesService.GetEmployeeInfo(evaluation.LastEvaluatorId),
                CreatedDate = evaluation.CreatedDate,
                ModifiedDate = evaluation.ModifiedDate
            };

            return evaluationViewModel;
        }

        private IEnumerable<EvaluationViewModel> GenerateEvaluationViewModels(IEnumerable<Evaluation> evaluations)
        {
            ICollection<EvaluationViewModel> evaluationViewModels = new List<EvaluationViewModel>();

            foreach (var evaluation in evaluations)
            {
                evaluationViewModels.Add(GenerateEvaluationViewModel(evaluation));
            }

            IEnumerable<EvaluationViewModel> evaluationViewModelsEnumerable = new List<EvaluationViewModel>(evaluationViewModels);

            return evaluationViewModelsEnumerable;
        }

    }
}

EvaluationApp/Controllers/EvaluationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using AppServices.EmployeeAuthentication;
using AppServices.Evaluations;
using AppServices.EvaluationsForms;
using AppServices.EvaluationStatistics;
using DomainModel.Domain;
using EvaluationApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace EvaluationApp.Controllers
{
    public class EvaluationsController : Controller
    {
        private readonly IEvaluationFormsService evaluationFormsService;
        private readonly IEvaluationsService evaluationsService;
        private readonly IAuthenticationService authenticationService;
        private readonly IEmployeesService employeesService;
        private readonly IEvaluationStatisticsService statisticsService;

        public EvaluationsController(
            IEvaluationFormsService evaluationFormsService,
            IEvaluationsService evaluationsService,
            IAuthenticationService authenticationService,
            IEmployeesService employeesService,
            IEvaluationStatisticsService statisticsService
            )
        {
            this.evaluationFormsService = evaluationFormsService;
            this.evaluationsService = evaluationsService;
            this.authenticationService = authenticationService;
            this.employeesService = employeesService;
            this.statisticsService = statisticsService;
        }

        [HttpGet]
        public IActionResult DeleteModal(int id)
        {
            Evaluation evaluation = evaluationsService.GetEvaluationById(id);
            EvaluationViewModel evaluationViewModel = GenerateEvaluationViewModel(evaluation);

            return View("DeleteModal", evaluationViewModel);
        }

        //[HttpPost("{evaluationId}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DoDelete(int id)
        {
            evaluationsService.Delete(id);
            return RedirectToAction(nameof(Completed));
        }

        public IActionResult InProgress()
        {
            int loggedEmployeeId = authenticationService.GetCurrentUserId();
            var inProgressEvaluations = evaluationsService.GetInProgressEvaluationsForEvaluator(loggedEmployeeId);
            var evaluationViewModels = GenerateEvaluationViewModels(inProgressEvaluations);

            return View(evaluationViewModels);
        }
        public IActionResult Completed()
        {
            int loggedEmployeeId = authenticationService.GetCurrentUserId();
            var completedEvaluations = evaluationsService.GetCompletedEvaluationsForEvaluator(loggedEmployeeId);
            var evaluationViewModels = GenerateEvaluationViewModels(completedEvaluations);

            return View(evaluationViewModels);
        }

        [HttpGet]
        public IActionResult StartFormEvaluationModal(int id)
        {
            int currentEmployeeId = authenticationService.GetCurrentUserId();

            var vm = new StartEvaluationViewModel();
            vm.SelectedForm = id;
            vm.IsFormEnabled = false;
            vm.Name = "";

            vm.EmployeesList = employeesService.GetEmployeesToEvaluate(currentEmployeeId)
                            .Select(employee => 
                                    new SelectListItem { Text = employee.Name, Value = "" + employee.Id })
                            .ToList();
            vm.FormsList = evaluationFormsService.GetEnabledSharedFormsForEmployee(currentEmployeeId)
                           .Select(form => 
                                   new SelectListItem { Text = form.Name, Value = "" + form.Id, Selected = (form.Id == id) })
                                   .ToList();
            vm.IsEmployeeEnabled = true;
                                
              
            return View("StartEvaluationModal", vm);
        }

        [HttpPost]
        public IActionResult StartFormEvaluationModal(StartEvaluationViewModel evaluation)
        {
            var form = evaluationFormsService.GetEvaluationForm(evaluation.SelectedForm);
            int currentEmployeeId = authenticationService.GetCurrentUserId();

            var eval = new Evaluation
            {
                EvaluationName = evaluation.Name,
                FormName = form.Name,
                FormId = form.Id,
                EmployeeId = evaluation.SelectedEmployee,
                Sections = evaluationsService.MapFormSectionsToEvaluationSections(form.Sections),
                CreatedBy = currentEmployeeId,
                LastEvaluatorId = currentEmployeeId,
                ModifiedBy = currentEmployeeId,
                CreatedDate = DateTime.Now,
                ModifiedDate = DateTime.Now
            };
            evaluationsService.InsertEvaluation(eval);

            return RedirectToAction("Evaluate", new { id = eval.Id });
        }

        [HttpGet]
        public IActionResult Evaluate(int id)
        {
            var eval = evaluationsService.GetEvaluationById(id);
            EvaluationFormViewModel formVM = new EvaluationFormViewModel();
            formVM.Id = eval.Id;
            formVM.Sections = eval.Sections;
            formVM.FormName = eval.FormName;
            formVM.EvaluationName = eval.EvaluationName;
            formVM.EmployeeName = employeesService.GetEmployeeInfo(eval.EmployeeId).Name;
            formVM.IsCompleted = eval.IsCompleted;
            formVM.SectionScales = new Dictionary<int, SectionScaleViewModel>();
            //NOTE: each section has its own scale

            foreach (var section in eval.Sections)
            {
                var sectionScale = section.EvaluationScale;
                if (sectionScale != null)
                {
                    var scaleOptions = evaluationsService.GetEvaluationScaleOptionsFromScale(sectionScale.Id);
                    var scaleOptionsVM = new SectionScaleViewModel() { SectionId = section.Id};
                    var options = new List<SelectListItem>();                  
                    options.Add(new SelectListItem (){ Value = "0", Text = "Not Evaluated" });                  
                        
                   options.AddRange(scaleOptions.Select(option => 
                                                    new SelectListItem
                                                    {
                                                        Value = "" + option.Id,
                                                        Text = option.Name
                                                    })
                                                     .ToList());
                    scaleOptionsVM.ScaleOptions = options;

                    formVM.SectionScales[section.Id] = scaleOptionsVM;
                }
                
            }         

            return View("EvaluationForm", formVM);
        }

        //public ContentResult JSON()
        //{
        //    List<DataPoint> dataPoints = new List<DataPoint>();

        //    var statistics = statisticsService.GetStatisticsForFormAndEmployee(1, 1);

        //    int i = 0;

        //    foreach (var evaluation in statistics.ProgressEvaluations)
        //    {
        //        foreach (var section in evaluation.ProgressSections)
        //        {
        //            dataPoints.Add(new DataPoint(i++, section.SectionAverageGrade.Value));
        //        }
        //    }

        //    JsonSerializerSettings _jsonSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore };
        //    return Content(JsonConvert.SerializeObject(dataPoints, _jsonSetting), "application/json");
        //}

        [HttpPost]        
        [Route("Evaluations/UpdateEvaluation", Name = "UpdateEvaluation")]
        public IActionResult UpdateEvaluation([FromBody]EvaluationData evaluationData)
        {
            ResponseData responseData = new ResponseData { Status = Ok().StatusCode, IsError = false, Text = "Evaluation saved successfully" };
            if (ModelState.IsValid)
            {
                try
                {
                    evaluationsService.UpdateEvaluationData(evaluationData);
                }
                catch (Exception e)
                {
                    responseData = new ResponseData { Status = (int)HttpStatusCode.NotModified, IsError = true, Text = "Failed to save evaluation." };
                }
                return Ok(responseData);               
            }

            return BadRequest();
        }

        private EvaluationViewModel GenerateEvaluationViewModel(Evaluation evaluation)
        {
            EvaluationViewModel evaluationViewModel = new EvaluationViewModel
            {
                Id = evaluation.Id,
                EvaluationName = evaluation.EvaluationName,
                FormName = evaluation.FormName,
                IsCompleted = evaluation.IsCompleted,
                Sections = evaluation.Sections,
                Employee = employeesService.GetEmployeeInfo(evaluation.EmployeeId),
                LastEvaluator = employeesService.GetEmployeeInfo(evaluation.LastEvaluatorId),
                CreatedDate = evaluation.CreatedDate,
                ModifiedDate = evaluation.ModifiedDate
            };

            return evaluationViewModel;
        }

        private IEnumerable<EvaluationViewModel> GenerateEvaluationViewModels(IEnumerable<Evaluation> evaluations)
        {
            ICollection<EvaluationViewModel> evaluationViewModels = new List<EvaluationViewModel>();

            foreach (var evaluation in evaluations)
            {
                evaluationViewModels.Add(GenerateEvaluationViewModel(evaluation));
            }

            IEnumerable<EvaluationViewModel> evaluationViewModelsEnumerable = new List<EvaluationViewModel>(evaluationViewModels);

            return evaluationViewModelsEnumerable;

EvaluationApp/Views/Employees/Completed.cshtml
@model IEnumerable<EvaluationApp.Models.EvaluationViewModel>
<br /><br />
<script>

</script>
<div class="container">
    <div class="row">
        <div class="table-responsive">
            <table class="table table-hover" id="table_id">
                <thead>
                    <tr>
                        <th>Evaluation Name</th>
                        <th>Evaluation Form</th>
                        <th>Employee</th>
                        <th>Last Evaluator</th>
                        <th class="no-sort">Actions</th>
                    </tr>
                </thead>
                <tbody id="myTable">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <a asp-controller="Evaluations" asp-action="DetailsCompleted" asp-route-evaluationId="@item.Id">@item.EvaluationName</a>
                            </td>
                            <td>@item.FormName</td>
                            <td>@item.Employee.Name</td>
                            <td>@item.LastEvaluator.Name</td>
                            <td>
                                <a asp-controller="Evaluations" asp-action="DetailsCompleted" asp-route-evaluationId="@item.Id" data-toggle="tooltip" data-placement="bottom" title="View Evaluation"><img src="~/images/view.png" /></a>
                                <a data-toggle="tooltip" data-placement="bottom" title="Delete Evaluation">
                                    <img data-toggle="modal" data-id="@item.Id" data-target="#exampleModal" src="~/images/cancel.png" />
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div id="confirmModal" class="modal-content">
        </div>
    </div>
</div>

<script>
    $('#exampleModal').on('show.bs.modal', function (e) {
        $('#confirmModal').load('@Url.Action("DeleteModal", "Evaluations")/' + $(e.relatedTarget).data('id'));
        $('#exampleModal').modal('show');
})
</script>

EvaluationApp/Views/Employees/EmployeeProgress.cshtml
@model AppServices.EvaluationStatistics.EvaluationFormStatistics


<br>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <!-- Nav tabs -->
            <div class="card">
                <ul class="nav nav-tabs" role="tablist">
                    @{
                        var idx = 0;
                        var defaultTab = 0;
                    }
                    @foreach (var crtSection in Model.SectionStatistics)
                    {
                        var tabId = "tab" + idx;
                        var tabRef = "#" + tabId;
                        var aClass = "nav-link";
                        var selectedArea = "";
                        if (idx == defaultTab)
                        {
                            aClass += " active show";
                            selectedArea = "aria-selected=\"true\"";
                        }
                        <li class="nav-item">
                            <a href="@tabRef" aria-controls="@tabId" role="tab" data-toggle="tab" class="@aClass" @selectedArea>
                                @crtSection.Name
                            </a>
                        </li>
                        idx++;
                    }
                </ul>
                <!-- Tab panes -->
                <div class="tab-content">
                    @{
                        idx = 0;
                        var chartId = "ct-chart";
                    }
                    @foreach (var crtSection in Model.SectionStatistics)
                    {
                        var tabClass = "tab-pane";
                        if (idx == defaultTab)
                        {
                            tabClass += " active show";
                        }
                        string anchorTarget = "tab" + idx;
                        <div role="tabpanel" class="@tabClass" id="@anchorTarget">
                            <div id="@chartId"></div>
                        </div>
                        chartId += idx;
                        idx++;
                    }
                </div>
            </div>
        </div>
    </div>
</div>

<br>
<link href="@Url.Content("~/css/DetailsCompleted.css")" rel="stylesheet" type="text/css" />

<script>
    //var data = {

    //    labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    //    series: [
    //        [5, 2, 4, 2, 0]
    //    ]
    //};

    var options = {
        //width: 1000,
        //height: 900,
    };


    var i = 0;
    var chartId = "#ct-chart";

    @*for (i = 0; i < @Model.SectionStatistics.Count; i++)
    {
        var data = {
            labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
            series: [
                [5, 2, 4, 2, 0]
            ]
        };

        new Chartist.Line(chartId, data, options);
        chartId += i;
    }*@
    var sectionIndex = 0;


    @foreach (var sectionStatistics in @Model.SectionStatistics)
    {
         <text>
            var sectionLabels = [];
            var sectionSeries = [];
         </text>

        @foreach (var sectionStatisticsEntry in sectionStatistics.SectionStatisticsEntries)
        {
            <text>
    sectionLabels.push('@sectionStatisticsEntry.Date.ToString("dd/MM/yy")');

    sectionSeries.push(@sectionStatisticsEntry.AverageGrade.Value);

            </text>
        }

        <text>
    var data = {
        labels: sectionLabels,
        series: [sectionSeries]
    };

    new Chartist.Line(chartId, data, options);
    chartId += i;
    i++;
    </text>
    }
</script>

<div>
    <a asp-action="Index">Back to Evaluation Forms</a>
</div>

EvaluationApp/Views/Employees/InProgress.cshtml
@model IEnumerable<EvaluationApp.Models.EvaluationViewModel>


<br /><br />
<div class="container">
    <div class="row">
        <div class="table-responsive">
            <table class="table table-hover" id="table_id">
                <thead>
                    <tr>
                        <th>Evaluation Name</th>
                        <th>Evaluation Form</th>
                        <th>Employee</th>
                        <th>Last Evaluator</th>
                        <th class="no-sort">Actions</th>
                    </tr>
                </thead>
                <tbody id="myTable">
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <a asp-controller="Evaluations" asp-action="DetailsInProgress" asp-route-evaluationId="@item.Id">@item.EvaluationName</a>
                            </td>
                            <td>@item.FormName</td>
                            <td>@item.Employee.Name</td>
                            <td>@item.LastEvaluator.Name</td>
                            <td>
                                <a asp-controller="Evaluations" asp-action="DetailsInProgress" asp-route-evaluationId="@item.Id" data-toggle="tooltip" data-placement="bottom" title="View Evaluation"><img src="~/images/view.png" /></a>
                                <a data-toggle="tooltip" data-placement="bottom" title="Continue Evaluation">
                                    <img src="~/images/start.png" onclick="location.href='@Url.Action("Evaluate", "Evaluations", new { id = item.Id})'" />
                                </a>    
                                <a data-toggle="tooltip" data-placement="bottom" title="Delete Evaluation">
                                    <img data-toggle="modal" data-id="@item.Id" data-target="#exampleModal" src="~/images/cancel.png" />
                                </a>                                
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div id="confirmModal" class="modal-content">
        </div>
    </div>
</div>

<script>
    $('#exampleModal').on('show.bs.modal', function (e) {
        $('#confirmModal').load('@Url.Action("DeleteModal", "Evaluations")/' + $(e.relatedTarget).data('id'));
        $('#exampleModal').modal('show');
})
</script>

EvaluationApp/Views/Employees/StartEvaluationModal.cshtml
@{
    Layout = null;
}
@model EvaluationApp.Models.StartEvaluationViewModel

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLabel">Start Evaluation</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-body">
    <form asp-controller="Evaluations" asp-action="StartFormEvaluationModal" method="post">
        <div class="form-group">
            <label for="name">Evaluation Name</label>
            <input type="text" asp-for="Name" class="form-control" id="name">
        </div>
        <div class="form-group">
            <label>Evaluation Form</label>
            <select id="evaluationFormsSelect" data-placeholder="Evaluation Forms"
                    class="chosen-select form-control" tabindex="-1"
                    asp-for="SelectedForm" asp-items="Model.FormsList"
                    disabled="@(Model.IsFormEnabled==false)"></select>
            @*<input type="hidden" asp-for="@Model.SelectedForm"/>*@
        </div>
        <div class="form-group">
            <label>Employee</label>
            <select id="employeeSelect" data-placeholder="Employees"
                    disabled="@(Model.IsEmployeeEnabled==false)" asp-for="SelectedEmployee" asp-items="Model.EmployeesList"
                    class="chosen-select form-control" tabindex="-1"></select>
            <input type="hidden" asp-for="@Model.SelectedEmployee" />
        </div>
        @*<button type="submit" class="btn btn-primary" data-dismiss="modal"
                    onclick="location.href='@Url.Action("StartEvaluationModal", "Evaluations")'">
                Start Evaluation
            </button>*@
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <input type="submit" value="Start Evaluation" class="btn btn-primary" />
        </div>
    </form>
</div>

<script>
    $("#evaluationFormsSelect").chosen();
    $('#employeeSelect').chosen();
</script>

EvaluationApp/Views/Employees/ViewEmployeeProgressModal.cshtml
@{
    Layout = null;
}
@model EvaluationApp.Models.EmployeeProgressViewModel
<!-- Modal -->
<div>
    <div class="modal-header">
        <h4 class="modal-title">View Employee Progress</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
    </div>
    <div class="modal-body">
        <form asp-controller="Employees" asp-action="EmployeeProgress" method="get">
            <div class="form-group">
                <label>Evaluation Form</label>
                <select id="evaluationFormsSelect" data-placeholder="Evaluation Forms"
                        class="chosen-select form-control" tabindex="-1"
                        asp-for="SelectedForm" asp-items="Model.FormsList"
                        disabled="@(Model.IsFormEnabled==false)"></select>
                @*<input type="hidden" asp-for="@Model.SelectedForm"/>*@
            </div>
            <div class="form-group">
                <label>Employee</label>
                <select id="employeeSelect" data-placeholder="Employees"
                        disabled="@(Model.IsEmployeeEnabled==false)" asp-for="SelectedEmployee" asp-items="Model.EmployeesList"
                        class="chosen-select form-control" tabindex="-1"></select>
                <input type="hidden" asp-for="@Model.SelectedEmployee" />
            </div>
            @*<button type="submit" class="btn btn-primary" data-dismiss="modal"
                        onclick="location.href='@Url.Action("StartEvaluationModal", "Evaluations")'">
                    Start Evaluation
                </button>*@
            <div class="form-group">
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="submit" value="View Progress" class="btn btn-primary" />
                </div>
            </div>

        </form>
    </div>

</div>

<script>
    $("#evaluationFormsSelect").chosen();
    $('#employeeSelect').chosen();
</script>